### ISSUE TITLE
Try community build buildid = 20151126180429

### ISSUE THREAD

**Issue by dattaz** [mozfr/buildscommunautaires#1]
=> http://builds.firefoxos.mozfr.org/opencebay/temp/2.1/
it's a fixed build, so please wipe data before flashing and report that is you url update in settings->devs
Thanks !

**Comment by dattaz** [comment]
test form => https://dattaz.fr/mozilla/buildscommunautaires/try_communauty_build/try_build.php?buildid=20151126180429

**Comment by GuillaumeHM** [comment]
Hello Dattaz, I'm volunteer to test new builds on my OpenC EU. Can you contact me on Diaspora ? I have some questions because I'm new on FirefoxOS.

**Comment by frafra** [comment]
Downgrade from 2.2 to 2.1 build 20151126180429. FF OS asks me for a system upgrade (114,68 MB). Should I accept it?

**Comment by mossroy** [comment]
frafra, first of all, you have to be aware that you should not keep your data if you do a downgrade : even if it might work in many cases, it can also generate bugs that would be very difficult to understand. So please wipe your data with any downgrade.

And no, you should not accept this system upgrade : it's always the case for test builds and should disappear when it's officially released (and properly configured)

**Comment by frafra** [comment]
SIM not seen, even if GSM signal strength is shown. GPS doesn't seem to work.
Test form allows you to select more than one result sometimes (you can check both "doesn't work" and " Dont know" under "Share internet by usb"). There are some issues with vars ("{{ $date }}") and results (broken link at the end)

@mossroy Thank you :) I'll try to reset everything and retest this build. Is there a preferred way to do it?

**Comment by mossroy** [comment]
If I remember correctly, when you're in "recovery mode" (after starting with power and volume up buttons), there is an option to "wipe data" or something similar

**Comment by GuillaumeHM** [comment]
I confirm the behaviour, I had the same. I accepted the upgrade and it was installed correctly but I have not seen a difference in the system.

**Comment by frafra** [comment]
I wiped out everything from recovery mode, I updated (without rebooting), and I can say that SIM, phone calls and SMS work! I can't test GPS properly. Tethering wifi/usb don't work for me.

No output from `adb logcat` when I enable or disable tethering wifi or usb.

**Comment by dattaz** [comment]
@GuillaumeHM if you accept you will have a old build :/

**Comment by dattaz** [comment]
i know there is some issue with form, i will try to correct this.
@GuillaumeHM can you try Share internet by wifi and Share internet by usb ?

**Comment by GuillaumeHM** [comment]
OK, so I have to install the 2.1 again. I don't need to wipe /data because I did it at the first install. Then I will test internet share and tell you the result. Happy new year every one !

**Comment by GuillaumeHM** [comment]
So the result is I can't get it work on USB nor on Wifi. On USB no ethernet card are mounted on my computer, but filesystems volumes of my sdcards are. On wifi I can't see the SSID from my computer that I configured on the phone.

**Comment by dattaz** [comment]
i've got confirmation that share internet is working on wifi.

@GuillaumeHM can you try if you have the same problem with currant build at  http://builds.firefoxos.mozfr.org/opencebay/2.1 ?
