### ISSUE TITLE
Can't connect to email box using Let's Encrypt

### ISSUE THREAD

**Issue by M5oul** [mozfr/buildscommunautaires#15]
B2G 2.6
I'm using a YunoHost server with Let's Encrypt certificate.
I can't connect to with email app.
It was working with CaCert certificate with FFOS 1.3.
I will try soon with B2G 2.6 and CaCert.
`ca-certificates` package must be update to include Let's Encrypt certs?

**Comment by mossroy** [comment]
Strange : on Firefox OS 2.5 I have no issue to use Let's Encrypt certificates for the calendar app (did not try for the email app).
It would be surprising that the CA certificates would be more up-to-date on 2.5 than on 2.6?

**Comment by M5oul** [comment]
Ok, may be I encounter an other issue to connect to the email account.

**Comment by M5oul** [comment]
[Succeed](https://yunohost.org/#/email_configure_client_fr)!
