### ISSUE TITLE
FOTA update not working on nightly builds (EU version)

### ISSUE THREAD

**Issue by djibux** [mozfr/buildscommunautaires#3]
**Problem**

Update via FOTA does not work.

**Error**

After downloading an update, the phone reboots and displays the following error.

```
Finding update package…
E: unknown volume for path [/updates/fota/update.zip] 
E: Can't mount /updates/fota/update.zip
Package corrupt.
Update failed.
```

**Workaround**

Downloading the update.zip and installing it manually from the recovery does the job.

**Comment by spx7** [comment]
Hi there,

I had a nightly builds running, made an FOTA (installed Update)... then Device (ZTE OpenC) rebooted and never got it done.

Error:
Meaning, it booted, showed lockscreen.
a) if you unlock -> reboot
b) if you dont unlock -> reboot

that was it.

Workaround: Power+VolumeUp -> RecoveryMode
use SDcardUpdate with update.zip

anyone else had that?

**Comment by dattaz** [comment]
yep know issue, code was backout on mozilla side.
Build of 07/01/2016 work. SO you can sideload it and have your phone working.
