### ISSUE TITLE
Tester la build 2.5 buildid=20160109164114

### ISSUE THREAD

**Issue by dattaz** [mozfr/buildscommunautaires#4]
Hop, une branche 2.5 existe toujours! elle est builder avec spark.
En plus de la précédente ( #2 )  qui n'a pas été distribuer par manque de de test fiable , cette build inclus les patch pour avoir une heure correct au redémarrage.

Il faudrait la tester en vérifiant particulièrement 3 point :
- que timekeep fonctionne bien, pour cela il faut lancer des scripts particulier sur le téléphone => https://github.com/micgeri/zte-openc-add-timekeep-at-boot MERCI à @micgeri !
- que le bluetooth fonctionne bien, pour cela il faut lancer des scripts particulier sur le téléphone => https://github.com/micgeri/zte-openc-switch-bluedroid MERCI à @micgeri !

La build est dispo ici : http://builds.firefoxos.mozfr.org/openc/temp/2.5/ elle se flash comme les autres.
Merci !

**Comment by dattaz** [comment]
Merci de remplir le formulaire de test https://dattaz.fr/mozilla/buildscommunautaires/try_communauty_build/try_build.php?buildid=20160109164114
Si vous avez des problèmes, posez vos questions/remarques etc.. ici

**Comment by sergio-car** [comment]
J'ai testé la build 2.5 que tu as déposé sur mozfr.org,
elle semble bien résoudre le bug de la date et l'heure
par contre je n'utilise pas le bluetooth, et par conséquent je n'ai pas testé
impossible de remplir le formulaire sur le site dattaz.fr, j'ai systématiquement un time out

Merci pour le travail accompli

**Comment by pipoprods** [comment]
J'ai installé le build. J'attends d'avoir appliqué les patches (heure et Bluetooth) avant de me lancer dans les tests.

Petite question au passage, les outils de @micgeri téléchargent depuis comebuy. C'est bon pour un Open-C FR ? (il me semblait que c'était plutôt pour la version EU)

Le site de comebuy est en panne pour l'instant. J'espère qu'il reviendra bientôt que je puisse me lancer.

**Comment by sergio-car** [comment]
Je n'ai pas eu à appliquer les patch, il suffit de saisir le code pin après le démarrage du téléphone et la date et l'heure se mettent à jour automatiquement sans WIFI et sans la 3G.

**Comment by pipoprods** [comment]
Oui, ça c'est le comportement habituel. Le patch permet justement de modifier ce comportement pour que le téléphone reste à l'heure d'un reboot à l'autre.

**Comment by sergio-car** [comment]
Avant cette nouvelle version, j'étais obligé d'utiliser l'astuce du wifi ou de la 3G, car même identifié chez l'opérateur en saisissant le code PIN, l'heure et la date étaient fausses.

**Comment by pipoprods** [comment]
Avec le patch, le téléphone est à l'heure immédiatement après reboot (ça va me faire bizarre de plus voir le 0h45…)

**Comment by sergio-car** [comment]
Question à 1 euro, comment s'y prend-t-on pour appliquer un patch ?

**Comment by pipoprods** [comment]
C'est détaillé là : https://github.com/micgeri/zte-openc-add-timekeep-at-boot

En gros, il faut cloner ce dépôt (et l'autre - voir le message de dattaz tout en haut de la page - pour le Bluetooth), extraire le "boot.img" du pack root qui provient du site ZTE, lancer le script qui modifie l'image de boot et enfin lancer le script qui flashe l'image.

**Comment by ghost** [comment]
Je confirme pour le site de téléchargement de Comebuy (down.comebuy.com).
Il faudra donc patienter un peu pour le Bluetooth.

**Comment by sergio-car** [comment]
nob900, J'ai lu le détail de la procédure timekeep-at-boot
Il faut déjà avoir une machine tournant sous linux ou mac osx et essayer de récupérer des fichiers à droite ou à gauche, et se 'démerder' avec les instructions qui manquent de précision. Je vais essayer et vous tiens au jus ...

**Comment by dattaz** [comment]
sorry pour le site pour le formulaire, j'avais pas d'autre choix que le hors-ligne, ça doit être revenu.

**Comment by genma** [comment]
nob900 me signale sur Diaspora  
"Je suis confronté à un comportement gênant avec ce build.
Apparemment Gaia plante régulièrement. La conséquence la plus visible (et gênante) c’est que mon téléphone se trouve déconnecté du réseau. Si je déverrouille l’écran d’accueil, il me demande le code PIN et se reconnecte correctement. Je dirais que ça arrive toutes les 2h.
Je n’ai pas ce comportement avec le build 2.5 du mois d’octobre (2015103114563).
Est-ce que d’autres ont le même problème ?"

**Comment by pipoprods** [comment]
Merci d'assurer le secrétariat Genma :-D

J'attendais d'éventuels retours pour poster ici…

**Comment by ghost** [comment]
Bonjour à tous,

J'ai mis à jour les scripts pour le Bluetooth. Vu que le site down.comebuy.com n'est toujours pas revenu, le script récupérera les fichiers depuis une autre source. Vous pouvez mettre à jour.

**Comment by olivierkeke** [comment]
Bonjour,

J'ai testé les deux patchs, tout fonctionne chez moi. Merci dattaz et micgeri ! 
Pourquoi cette version ne rentre pas sur le canal aurora ?

**Comment by pipoprods** [comment]
Testé et rempli le formulaire.

Tout fonctionne bien à l'exception du crash Gaia de temps en temps (en ce moment c'est ~ 1 fois par jour).

Peut-être lié au firmware du téléphone, je n'ai pas installé le firmware qui corrige les problèmes de plantage en cours d'appel (mon téléphone n'a jamais planté en cours d'appel) et qui fait que la LED ne s'allume plus pendant la charge.

**Comment by pipoprods** [comment]
Ma note « Tout fonctionne bien » concerne également les patches de @micgeri .

**Comment by pjoulot** [comment]
Les addons semblent fonctionner dans cette version contrairement à la précédente.
Je testerai le build cette semaine pour faire un retour plus complet et pas seulement sur un seul point.

**Comment by grandsion** [comment]
J'ai installé le build sur mon téléphone tout neuf et fais les 2 patchs 
l'heure fonctionne après reboot du téléphone et le bluetooth fonctionne aussi
il n'y que certains jeux du marcketplace qui ne fonctionne pas
par exemple Candy Rain 2 se charge puis l'écran reste noire avec uniquement le logo du jeu en haut

**Comment by dattaz** [comment]
build poussé !
merci à tous !

**Comment by pipoprods** [comment]
En voilà une bonne nouvelle !

De mon coté je n'ai plus vraiment de plantage de Gaia depuis que j'ai installé le firmware B03 de ZTE. J'ai écrit « plus vraiment » car j'ai quand même eu un plantage en une semaine.

Pour la mise-à-jour j'ai utilisé l'outil de @micgeri : https://github.com/micgeri/zte-openc-flash-modem.git

**Comment by gabe-fr** [comment]
Salut. Comment être averti de la prochaine session des tests de la nouvelle image 2.5 ?

**Comment by dattaz** [comment]
s'inscrire sur cette issue sera suffisant.
je mettrais ici un lien vers la build

**Comment by dattaz** [comment]
Bonjour à tous,
on aurait besoin de retour sur une mise à jour qui remplacerait les scripts, et  micgeri cherche des testeurs qui ONT APPLIQUÉ les scripts : https://github.com/mozfr/buildscommunautaires/issues/5
merci :)

**Comment by gabe-fr** [comment]
Salut. Les deux scripts génèrent chacun un _boot.img_ , doit on lancer la mise à jour du téléphone un script après l'autre ? Ou doit-on les cumuler puis envoi vers le tel ?

**Comment by ghost** [comment]
Salut,

Il est possible de cumuler en procédant ainsi :
1) Génération du boot.img intégrant le service timekeep (exécuter uniquement le 1er script du timekeep)
2) Copie du boot.img généré dans zte-openc-switch-bluedroid/update-bootimage/put-files-here

**Comment by gabe-fr** [comment]
Salut. J'ai un problème à la fin : 

> failed to copy '/home/gabe-fr/ZTE_Open_C/zte-openc-switch-bluedroid-master/switch-openc-to-bluedroid/put-files-here/boot.img' to '/storage/sdcard/boot_bth.img': **Read-only file system**

Une idée ? Merci

**Comment by dattaz** [comment]
adb remount avant

**Comment by gabe-fr** [comment]
Le problème est sur ces lignes : 

> # Attributions des utilisateurs/droits sur les fichiers
> 
> echo "$0 : Attribution des permissions sur les fichiers..."
> adb shell chmod 644 /system/etc/bluetooth/\* &&
> adb shell chmod 644 /system/lib/libbt-\* &&
> adb shell chmod 644 /system/lib/hw/audio.a2dp.default.so &&
> adb shell chmod 644 /system/lib/hw/bluetooth.default.so &&
> adb shell chmod 644 /system/vendor/lib/libbt*.so &&

Ca me sort ça : 

> Unable to chmod /system/lib/libbt-hci.so: Read-only file system

**Comment by gabe-fr** [comment]
Y'a t'il un moyen d'avoir un shell en root directement sur la partition racine du téléphone (comme un _chroot_ par exemple) ?
Ça me permettrait peut-être de faire les changements ci-dessus.

**Comment by ghost** [comment]
Bonjour gabe-fr,

As-tu rooté ton téléphone avec l'utilitaire de ZTE ?

**Comment by olivierkeke** [comment]
Bonjour,
Je viens de me rendre compte que je n'ai plus l'adaptation automatique de la luminosité de l'écran. Ça doit probablement dater d'une build antérieure à la 2.5 mais je ne l'avais pas remarqué jusqu'à présent... Le problème est connu ?
A+
Olivier

**Comment by gabe-fr** [comment]
@micgeri Oui, root avec le logiciel ZTE et mise à jour par carte SD de 1.3 vers 2.5.
En fait, ne me rappelant plus si j'avais appliqué le patch "keeptimer" (celui du bluetooth oui), j'ai voulu recommencer les étapes. Mais ça c'était aussi après avoir appliqué ton nouveau patch de boot...
Je pense que tout ça a fait un mic-mac, je vais sûrement devoir faire une remise à zéro totale...

**Comment by ghost** [comment]
@olivierkeke Je me suis dit la même chose au départ, puis un contributeur (je n'arrive pas à me rappeler de son nom) m'a expliqué que c'est juste un changement de comportement à partir de la version 2.5 : l'adaptation va se faire, mais plus en douceur. Si tu veux plus d'infos, tu peux voir le [bug 1179353 sur Bugzilla@Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1179353).

@gabe-fr Pas nécessairement à 0. Cependant, je trouve bizarre que tu aies un problème de partition /system en lecture-seule, sachant que le script fait lui-même un adb remount avant l'envoi des fichiers, et le changement des permissions.
Si j'ai bien suivi ton précédent post, tu avais déjà appliqué le patch bluetooth sur l'image boot, mais tu ne te rappelais pas si tu avais appliqué celui du timekeep, c'est bien cela ?

**Comment by gabe-fr** [comment]
Salut, oui c'est bein cela. J'ai appliqué le patch "timekeep" après coup. Et peut-être même après ton nouveau patch "recovery_update" si ça se trouve, je ne me souviens plus.

En tout cas j'ai monté la partition système dans un terminal, les fichiers mis à jour sont bien présents (date+heure courante par rapport aux autres), et ils ont les mêmes droits que les autres.
Par contre le bluetooth ne fonctionne plus maintenant même après ré-application du patch.

J'ai essayé de remettre le téléphone en réglage d'usine mais je n'ai pas réussi.
L'archive ZTE me jette en signalant un problème de vérification de signature.
La [procédure de Mozilla](https://developer.mozilla.org/fr/Firefox_OS/Guide_Telephone_Developpeur/ZTE_OPEN_C#J'ai_brické_mon_téléphone) est plutôt lourde, faudra que je prenne le temps.

Merci.

**Comment by ghost** [comment]
Ok. Je suppose que les fichiers du Bluetooth sont toujours présents sur ton Open C (/system/lib/libbt*, /system/etc/bluetooth/*, etc.).
Si tel est le cas, appliques la recovery_update uniquement et testes à nouveau stp, avant d'envisager une remise à 0.

**Comment by lool-lauris** [comment]
Bonjour Tout le Monde,

J'utilise la 2.5 sur un open C FR depuis 2 semaines maintenant (auparavant j'avais un open C ebay sous la 1.3).
Bon déjà, absolument rien de comparable avec la 1.3 ... je trouve globalement cette version super bien (design général, possibilité de copier-coller, navigation internet, messagerie e-mails, téléchargement des pièces jointes, gestion batterie plus économe, ...)

Après avoir installé la 2.5 buildid=20160109164114, les 2 patches timekeep & bluedroid, j'ai installé le "recovery_update_timekeep_bluetooth_led.zip".

Quelques petits soucis avec le bluetooth même si globalement ça fonctionne relativement bien. Les périphériques sont bien reconnues et le téléphone est lui bien reconnu par les autres.
Les principaux soucis viennent de l'utilisation avec l'autoradio de la voiture ; 1 ou 2 freezes, quelques redémarrages ...
Également, il arrive fréquemment qu'il ne soit plus possible d'activer ou désactiver le bluetooth par l'écran de notification (celui qui s'affiche en tirant de haut en bas), il faut passer par les paramètres de l'appareil.

Aucun problème constaté avec la conservation de l'heure, que le téléphone soit en veille ou bien éteint puis rallumé.

J'ai constaté aussi que le réglage du volume sonore de "Sonneries et notifications" n'est pas toujours conservé.

Autre chose (positive), je peux recevoir des mms (accompagnés de photos) sans avoir à me raccorder à l'UMTS ou la WIFI (impossible avec mon autre open C ebay sous 1.3).

Ah oui, dernier point, il a fallu installer l'application Radio FM qui manquait.

Note globale : très satisfait par cette version (bon, en même temps en venant de la 1.3 ...).

**Comment by bwatt-fr** [comment]
Je viens d'installer le patch bluetooth (je n'ai perso jamais eu de problème avec la date et l'heure).
Mon bluetooth, qui ne fonctionnait plus depuis mon passage à la 2.6, remarche à nouveau : je peux l'allumer à nouveau et connecter le téléphone à mon ordinateur.
Par contre, la connexion à mon casque bluetooth ne fonctionne toujours pas (alors que ça fonctionnait quand mon bluetooth marchait avant). Il apparait toujours dans la liste des devices anciennement apairés, mais quand je clique sur le bouton, il ne se passe rien (je ne peux pas le désapairer par exemple). Je me dis que ça pourrait venir du fait qu'il était déjà connu par mon téléphone avant l'application du patch. Y a-t-il d'autres personnes qui avaient déjà un appareil appairé avant le patch ?
J'ai tâché de bidouiller le fichier /etc/bluetooth/audio.conf (où on peut activer/désactiver des interfaces si j'ai bien compris), mais ça n'a rien changé.

PS : déjà très content que mon bluetooth remarche pour certaines applications, merci pour le patch !

**Comment by HunterUrnam** [comment]
Au risque de passer pour un con mais où se trouve le dossier : put-files-here ?
Ensuite, comment exécuter update-bootimage.sh

Autant j'ai bien réussi à mettre le modem à jour, autant je nage complètement là.

**Comment by lool-lauris** [comment]
Salut,

Ce qui serait surtout très con, ce serait de rester assis sur son cul et 
de ne pas demander ... quand on ne sait pas, je trouve que c'est plutôt sain de 
demander !  =)

En fait, cela concerne la mise à niveau du bluetooth, le dossier 
"zte-openc-switch-bluedroid-master". Le dossier "put-files-here" se 
trouve ici : zte-openc-switch-bluedroid-master/switch-openc-to-bluedroid/

Si tu suis bien la manip indiquée, ça roule tout seul. Mais si tu as 
d'autres questions, n'hésite pas.

+++

lool

**Comment by HunterUrnam** [comment]
Je pensais que mon message, bien que supprimé quand je me suis rendu compte tardivement que les opé nécessitait Linux/Unbutu, serait passé inaperçu :D 
Le dossier put-files-here ne se trouvait pas dans zte-openc-switch-bluedroid-master/switch-openc-to-bluedroid/ quand j'ai regardé. Je l'avais créé moi même mais n'étais pas sûr de mon initiative.
Après avoir contacté micgeri, il a été rajouté et m'a confirmé la marche à suivre :)

Je vais tester via mac OS et son terminal. J'installe ADB rapidement et je vous tiens au courant.
Merci en tout cas à vous, c'est super plaisant.

**Comment by HunterUrnam** [comment]
Hum... ADB sur mac, c'est une vraie plaie.
ADB Devices n'est pas reconnu, donc le téléphone non plus. J'ai beau m'être penché dessus en ayant lu plein de pages qui expliquent comment faire, je n'y arrive toujours pas.

**Comment by lool-lauris** [comment]
Peut-être le moment de passer à GNU/Linux. Mac, c'est certainement pas 
foutu (basé sur Unix d'ailleurs) mais c'est malgré tout super fermé, une 
stratégie commerciale de captation certainement plus prégnante que celle 
de µsoft.

Tu devrais bien pouvoir trouver une machine qui traîne dans un coin ou 
chez un proche ...
=)

**Comment by HunterUrnam** [comment]
En fait c'est plus complexe. Mac OS n'a pas besoin du driver Google USB.
En revanche, en fonction de ta version d'OS (en l'occurrence j'ai un 10.6.8 et 10.10.5 à dispo) c'est le même "boxon" plus ou moins compliqué.
Déjà, JAVA7 ne peut être installé sur une version inférieur 10.7, j'ai réussi à bidouiller. Sauf qu'après c'est véritablement tout un micmac pour faire en sorte qu'ADB reconnaisse le périphérique usb sur lequel est branché le téléphone.
J'ai passé du temps sur les forums (principalement anglais/américain) et je n'ai pas réussi. C'est dommage parce que le Terminal est bien plus cool que sur Windaube.

Je vais faire une usb bootable je pense. Si je comprends bien une usb-bootable avec Unbutu me fera "bosser" sur un Linux. Depuis lequel, je pourrai installer adb.

**Comment by lool-lauris** [comment]
"Je vais faire une usb bootable je pense. Si je comprends bien une 
usb-bootable avec Unbutu me fera "bosser" sur un Linux. Depuis lequel, 
je pourrai installer adb."
Je n'ai jamais fait la manip depuis une clé usb mais je pense que c'est 
faisable !
=)

**Comment by jpgemble** [comment]
Je viens de saisir un bug sur cette version concernant l'enregistrement de vidéos.
Je n'ai pas été capable de trouver une build plus récente. Y en a-t'il une ? Y en aura-t'il une ?

**Comment by pololasi** [comment]
Testé et installé aujourd'hui.
Dans un premier temps le bluetooth n'était pas fonctionnel. J'avais juste oublié dans la partie Paramètres > Developpeurs > Debogage USB du ZTE Open C d’activer le débogage pour ADB et comme je tentai d’appliquer la mise a jour en 2.5 et le patch zte-openc-switch-bluedroid via adb forcément ça coinçait.
Pour moi seules les deux premières étapes ont étés  nécessaires :
    Procédure mise à jour boot.img
    Procédure envoi fichier vers téléphone
Je suppose que la dernière intitulée Procédure restauration pile bluetooth origine ne sert que pour revenir en arrière ?

**Comment by Monsieur-B** [comment]
J'ai installé cette build il y a quelques jours, ainsi que le patch Bluetooth (recovery_update_timekeep_bluetooth_led.zip).
Malheureusement, le bluetooth ne fonctionne pas, je n'arrive même pas à l'activer.
Autre détail que j'ai remarqué, à chaque fois que je redémarre mon téléphone, le clavier pour les SMS revient en "anglais" par défaut.

Autre chose assez gênante, dans l'application de gestion des fichiers, je n'ai trouvé aucun moyen pour transférer un ou plusieurs fichiers de la mémoire du téléphone vers la carte SD (et inversement…)

**Comment by mossroy** [comment]
J'ai installé cette version 2.5 aujourd'hui, et elle marche apparemment bien.
Le bluetooth semble fonctionner, mais il m'est arrivé qu'il plante. Dans ce cas, un reboot du téléphone le remet d'aplomb.
J'ai pu faire un transfert de fichier depuis mon PC, mais n'ai pas réussi à le faire vers le PC, ou depuis/vers un autre téléphone Firefox OS (Flame 2.5).
Concernant l'heure, elle est bien conservée après un reboot (même sans accès Wifi ou 3G) : c'est vraiment cool!
Je n'ai pas le problème de clavier qui revient en anglais.

**Comment by ghost** [comment]
@lool-lauris 
Je vois que tu as réussi à réinstaller l'app Radio FM, comment as-tu fait ?
Il y a tout un tas de bouiboui dans le Marketplace... :s

**Comment by lool-lauris** [comment]
@Petrusko 
Salut,
Tu trouveras la procédure pour installer l'appli "radio FM" ici => https://forums.mozfr.org/viewtopic.php?f=33&t=127146&p=807416#p807094
Bye,
lool

**Comment by ghost** [comment]
@lool-lauris 
Merci pour lien.
Cependant après un make, le répertoire "fm" n'apparait pas. Il se trouve seulement dans "disabled_apps". J'ai bien tenté de le déplacer dans "build", mais aucune sortie dans bluid_stage :'(

**Comment by lool-lauris** [comment]
@Petrusko 

Salut,
Ci-joint l'app fm.
Sers-toi de web-ide pour l'intégrer dans ton open-c.
Bye
lool

[fm.zip](https://github.com/mozfr/buildscommunautaires/files/1244504/fm.zip)

**Comment by ghost** [comment]
Ok merci pour ton lien (une nouvelle fois!).

Du coup je me suis mis le nez dans cette histoire de webide intégré au navigateur Firefox (Shift+F8).
Installé le simulateur Firefox OS 2.6.

1. Trouver le répertoire fm.gaiamobile.org contenu dans ce simulateur... situé (dossiers en MAJ à changer selon son environnement Windows) :
C:\Users\UTILISATEUR\AppData\Roaming\Mozilla\Firefox\Profiles\PROFILE.DEFAULT\extensions\fxos_2_6_simulator@mozilla.org\profile\webapps\fm.gaiamobile.org
Linux/Debian: /home/UTILISATEUR/.mozilla/........(idem)..............
2. Dézipper le contenu de application.zip dans un répertoire sur son bureau (par exemple).
3. On ouvre webide dans Firefox (Shift+F8). Puis "Ouvrir une application empaquetée", chercher le dossier qui contient les fichiers précédemment dézippés.
-->Maintenant un nouvel élément apparait dans "Mes Projets" à gauche, "FM Radio" qui est tout frais.
4. On branche son Open C, on clique dessus dans webide pour qu'on soit connecté à lui (adb+dev activé dans le tél)
5. Clic sur la Flèche en haut au milieu "Installer et lancer".
Paff voilà l'app dans son tél.

Sinon j'ai tenté d'ajouter ce truc dans le hackerplace (renommé en Radio FM pour le coup), je ne sais pas trop si ca marche ou pas... si ca peut faciliter la vie aux possesseurs de 2.5 sans se galérer avec webide... à voir si un jour ca apparait dans la liste ?...
J'espère ne pas avoir commis d'erreur de débutant, sinon ne pas hésiter ! Merci @lool-lauris et tous pour les coups de paluches :)
