### ISSUE TITLE
Tester update boot pour Open C FR (avec build 2.5 uniquement)

### ISSUE THREAD

**Issue by ghost** [mozfr/buildscommunautaires#5]
**Ceci s'adresse uniquement à ceux qui ont appliqué la build 2.5 récemment poussé par dattaz et utilisé les scripts (#4).**

Bonjour à tous,

Un zip a été généré. Son but est d'appliquer une image boot contenant les services timekeep et Bluetooth au démarrage de l'Open C FR. A termes donc, les scripts ne seront nécessaires que pour rajouter les fichiers du Bluetooth, voire plus du tout.

Ce zip s'applique comme n'importe quel update (en mode recovery), et est disponible à cette adresse : http://builds.firefoxos.mozfr.org/openc/recovery_update_timekeep_bluetooth_led.zip

Suite à l'application de ce zip, et après un moment d'utilisation, merci de remonter ici le résultat de vos tests (problèmes rencontrés, fonctionnement timekeep/Bluetooth, ou stabilité du téléphone).

**Edit :** Un autre problème est résolu par cet update (merci @Bonstra), mais je laisse le soin de découvrir ce dont il s'agit.

**Comment by olivierkeke** [comment]
Bonjour,
Après quelques jours d'utilisation :
- le téléphone est à l'heure après une nuit d'extinction ;
- le bluetooth a l'air de fonctionner : il s'active et se désactive sans problème mais je n'ai pas d'appareil pour tester la connexion ;
- la petite surprise a fonctionné pendant le rechargement :-) ;
- pas de pb de stabilité.
  A+
  Olivier

**Comment by grandsion** [comment]
Bonjour,
je viens de lancer le zip à travers la carte SD en mode recovery, je n'ai pour l'instant rien vu de significatif par rapport à avant,
c'est quoi la surprise ?

**Comment by HunterUrnam** [comment]
Bonjour,
J'ai bien récupéré la build 2.5 (20160109164114) de Dattaz et installé le zip.
De mon côté, le problème de l'heure est résolu, en revanche pas de bluetooth opérationnel :(

Stabilité OK

**Comment by pololasi** [comment]
Bonjour

Installé aujourd'hui via adb. Entièrement fonctionnel.
Pas de surprise sauf s'il s'agit de la LED qui re fonctionne.

**Comment by Monsieur-B** [comment]
Après l'application de ce patch, le bluetooth ne fonctionne toujours pas sur mon téléphone…

**Comment by mossroy** [comment]
Pour moi aussi, la LED re-fonctionne après application de ce patch

**Comment by donlencho** [comment]
Bonjour,
Pas sûr de comprendre, est-ce que cette update remplace l'utilisation des deux scripts renseignés dans l'issue #4 ? J'ai installé la build "20160109164114" sans souci (et la LED fonctionne), est-ce qu'il vaut mieux que j'installe ceci en plus ou que je passe par les scripts? Ou les deux?

Dans le même ordre d'idée, est-ce que ceci est toujours d'actualité pour cette build?
https://github.com/micgeri/zte-openc-flash-modem

Grand merci,
